version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  setup:
    docker:
      - image: circleci/node12.18.3-browsers
    steps:
      - checkout
      - node/install-yarn: true
      - run: node --version
      - run: yarn version

workflows:
  ci:
    jobs:
      - setup

